### ISSUE TITLE
undefined data-id

### ISSUE THREAD

**Issue by Troy420** [Troy420/CSP-Project#1]
I have a problem on my js code *i think*
When i click on the image sometimes it will show 'work-item-undefined.jpg' on the console log
I need help.

PS: If you need the html or the css just let me know

Here's a part of the code:
function eventListeners() {
  const ui = new UI();

  //show modal
  const links = document.querySelectorAll('.work-item__icon');

  links.forEach(function (item) {
    item.addEventListener('click', function () {
      ui.showModal();
    })
  })

// Constructor Function
function UI() {

}

UI.prototype.showModal = function () {
  event.preventDefault();
  if (event.target.parentElement.classList.contains('work-item__icon'));
  let id = event.target.parentElement.dataset.id;

  const modal = document.querySelector('.work-modal');
  const modalItem = document.querySelector('.work-modal__item');

  modal.classList.add('work-modal--show');
  modalItem.style.backgroundImage = `url(/img/work-item-${id}.jpg)`;
}

![image](https://user-images.githubusercontent.com/25684892/58195857-85817480-7cfb-11e9-9756-1869beca0702.png)

**Comment by duckzland** [comment]
wrap the function inside document ready event https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event

so it will ensure that the data- attributes is parsed and loaded into DOM
